from .Grid import *


def make_grids():
    return [
        MainKitchen(0, 0),
        FoodStand(1, "珍珠奶茶", 2),
        FoodStand(2, "臭豆腐", 0),
        EffectGrid(3, "fee", "收租"),
        FoodStand(4, "牛肉麵", 3),
        FoodStand(5, "八寶冰", 0),
        EventGrid(6),
        FoodStand(7, "鹹酥雞", 1, default_char_id=0),
        FoodStand(8, "鱔魚麵", 2),
        MainKitchen(9, 1),
        FoodStand(10, "滷肉飯", 2),
        FoodStand(11, "仙草芋圓", 0),
        EffectGrid(12, "switch", "合作"),
        FoodStand(13, "大腸包小腸", 3),
        FoodStand(14, "魷魚羹", 0),
        EventGrid(15),
        FoodStand(16, "木瓜牛奶", 1, default_char_id=1),
        FoodStand(17, "鼎邊銼", 2),
        MainKitchen(18, 2),
        FoodStand(19, "四神湯", 2),
        FoodStand(20, "筒仔米糕", 0),
        EffectGrid(21, "buy", "徵收"),
        FoodStand(22, "當歸麵線", 3),
        FoodStand(23, "棺材板", 0),
        EventGrid(24),
        FoodStand(25, "潤餅", 1, default_char_id=2),
        FoodStand(26, "蚵仔煎", 2),
        MainKitchen(27, 3),
        FoodStand(28, "甜不辣", 2),
        FoodStand(29, "小籠包", 0),
        EffectGrid(30, "rest", "過勞"),
        FoodStand(31, "切仔麵", 3),
        FoodStand(32, "羊肉爐", 0),
        EventGrid(33),
        FoodStand(34, "肉圓", 1, default_char_id=3),
        FoodStand(35, "薑母鴨", 2),
    ]
